### ISSUE TITLE
[Feature] Option to report on current week

### ISSUE THREAD

**Issue by tcassaert** [nikolassv/bartib#10]
I know we can use the `--from` and `--to`, but having a `bartib report --week` would be very convenient.

**Comment by nikolassv** [comment]
Thank you for the suggestion! I just added `current_week` and `last_week` as new flags for the `list` and `report` subcommands.

(https://github.com/nikolassv/bartib/commit/09c7d963bfad7aa00a4b5117e8eee4c0ff9518d7)
