### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by meinbaumm** [nikolassv/bartib#18]
First of all, I want to say thank you very much for such a wonderful project. I have been using it for almost 7 months, it is a very simple and powerful time management tool.

I have found some spelling mistakes in the comments or in the returned lines, which may complicate the process of working with bartib. I am willing to fix them in this issue with your permission, if you don't mind to give me permissions push my branch with the fixes.

**Comment by nikolassv** [comment]
Thank you for your kind words! I am glad you enjoy using bartib.

As I am not a native speaker I am more than willing to take any fixes and improvements concerning the texts. Could you just create a PR? I would merge soon.

**Comment by meinbaumm** [comment]
Thank you, I would like to create a PR, but I think I don't have enough permissions to do that, because 
```
ERROR: Permission to nikolassv/bartib.git denied to meinbaumm.
fatal: Could not read from remote repository.
```

**Comment by nikolassv** [comment]
I do not think this is a problem with bartib in particular but a problem with GitHub. Have you already forked the project successfully and created the change in your fork?

**Comment by meinbaumm** [comment]
Yes, of course, sorry, I completely forgot about that. I created a PR for you https://github.com/nikolassv/bartib/pull/20
