### ISSUE TITLE
Release is 1.0.1, but app reports 1.0.0

### ISSUE THREAD

**Issue by steev** [nikolassv/bartib#25]
Looks like on line 93 of src/main.rs, you set the version manually, but the cargo.toml says it should be 1.0.1.  

I kept thinking I was out of date, or the crate was out of date, until I cloned git and built it and got the same response of `bartib 1.0.0` from `bartib --version`; probably need to bump that in the next release as well.

**Comment by nikolassv** [comment]
Thank you for this finding! I fixed the display of the version in the master branch (https://github.com/nikolassv/bartib/commit/69a5bf2c9e32c141bec7a0b46acb624fee1263a0). It will be corrected in the next release.
