### ISSUE TITLE
Integration with 3rd party services like Toggl

### ISSUE THREAD

**Issue by snturk** [nikolassv/bartib#34]
Basic integration with time tracking services like Toggl can be implemented, I'm planning to implement that under this issue.

**Comment by nikolassv** [comment]
This seems like a nice feature, but I am not sure if the bartib application itself is the right place for it. If you plan to import and export activities from bartib to other time trackers and vice versa, it might be better to create an additional application. In this way, bartib would only comprise the core logic, while these additional application would allow the addition of activities from other trackers into the bartib file.
