### ISSUE TITLE
Allow for a default command, or make start the default?

### ISSUE THREAD

**Issue by neezer** [nikolassv/bartib#37]
I've been bitten quite a few times by typing in `bartib FLAGS_FOR_START` and getting errors because I didn't type `bartib start FLAGS_FOR_START`.

Would it be possible to have `start` be the default command if no sub command is explicitly provided?

Better yet, could that be configurable, so that those folks that want `list` or `report` to be the default can have their way too?

**Comment by nikolassv** [comment]
I am not sure, if a default command would be that helpful for the general user as this may also lead to some unexpected behavior. Even if there was a default command, I would select one, that does not change the bartib file.

I think in you situation the best way to improve your workflow, would be to define an alias in your `.bashrc` like `alias bs='bartib start'`. I for example have registered some aliases like `brt`, `bry`, `blt` and `bly` for todays and yesterday report and list.
