### ISSUE TITLE
Broken  link

### ISSUE THREAD

**Issue by mbaneshi** [nikolassv/bartib#39]
https://docs.rs/crate/bartib/misc/bartibCompletion.sh 

this link is not exist but it was mentioned in doc beneath `How to activate auto completion`

**Comment by nikolassv** [comment]
This seems to be a problem with how docs.rs creates the documentation and how it handles repository internal links. If you visit the [README.md](https://github.com/nikolassv/bartib/blob/master/README.md) on GitHub the link works fine.

I will close this as I do not see an issue here that I am able to solve.
