### ISSUE TITLE
`break` command: recording break times

### ISSUE THREAD

**Issue by simonsan** [nikolassv/bartib#42]
> As a user, I want to be able to interrupt an activity and record it as a break, so that I can easily get an overview of the amount and lengths of my breaks during e.g. a work day.

I tend to use the Pomodoro principle more often, these days. And for that, it would be also nice to be able to track my breaks as well. It would be also just good to have that as a statistical value, for later analysation. 

How I would imagine it to work is the following:
1. `bartib start` - start activity
2. `bartib break` - stop activity && start predefined break "activity"
3. `bartib continue` - stop break "activity" && start last activity before break
4. if `bartib start` called instead of continue, warn for ongoing break and ask if last activity + break should be stopped

**Comment by RossBarnie** [comment]
You can recreate this with the following:
```
$ bartib start -p 'Break' -d 'Lunch'
# ... have lunch ...
$ bartib continue 1
```
Users could add these as shell aliases to make it easier for frequent use. Personally I don't think there's anything that the bartib project *needs* to include to enable this and I would be hesitant to overload the `continue` subcommand with this extra use-case.

**Comment by nikolassv** [comment]
Thank for bringing this up, but I too do not think, we do really need a `break` command. I like the idea of a shell alias, as this could be a good way to personalize Bartib for many unique use cases.
