### ISSUE TITLE
Documentation for `bartib start --time` is unclear

### ISSUE THREAD

**Issue by rushmorem** [nikolassv/bartib#5]
At first I thought `--time`, in this case, means the target time I wanted to finish the task so I set that to a time in future. Bartib (incorrectly?) accepted that. Then I stopped the task before that start time only to end up with end time earlier than start time.

**Comment by nikolassv** [comment]
Thanks for bringing this to my attention! I am not quite sure now how to make the documentation more precise concerning this point. When I come up with some better explanation I will adjust it.
